feat: use kzg-rs for kzg point evaluation
alloy-rs/alloy pull request #1018
Opened 2024-07-04 20:22 UTC by leruaa

## Motivation

Closes #1017

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-07-04 21:42 UTC, mattsse requested changes
I'd like to keep c-kzg as "kzg" for now so we don't break anything just yet

2024-07-04 21:42 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +        }
these type defs should then be isolated in a separate module and conditionally exported, so that we don't have to do this multiple times

2024-07-04 21:42 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
>      pub fn validate(
is there a kzg-rs equivalent to this?

2024-07-05 14:50 UTC, leruaa commented on crates/eips/src/eip4844/sidecar.rs
>      pub fn validate(
No, but I'm on it.

2024-07-07 20:37 UTC, leruaa commented on Cargo.toml
> +bls12_381 = { git = "https://github.com/leruaa/bls12_381", branch = "msm_variable_base" }
These patches may be removed once https://github.com/succinctlabs/kzg-rs/pull/3 is merged.

2024-10-10 10:47 UTC, closed without merging