feat: make block struct generic over header type
alloy-rs/alloy pull request #1179
Opened 2024-08-22 16:56 UTC by mvares

This PR allows Header assumes a type based on generic.

Closes #1177

2024-08-22 17:23 UTC, mvares commented
hey @emhane, do you know why the CI is failing?

2024-08-22 17:36 UTC, emhane requested changes
need to make sure that all the implementations for `Block` will also work for the non-default type. may advice is to add default generics last, after you got everything compiling.

2024-08-22 21:19 UTC, emhane commented
sorry wasn't clear enough:

remove the default for the generic.
compile.
fix bugs.
add default generic.

that's how I usually do.

`Block::into_full_block` is only impl for default header generic now

2024-08-23 00:27 UTC, mvares commented
> sorry wasn't clear enough:
> 
> remove the default for the generic. compile. fix bugs. add default generic.
> 
> that's how I usually do.
> 
> `Block::into_full_block` is only impl for default header generic now

Hmm. Looks a good start.

2024-08-23 00:29 UTC, mvares commented
@emhane, maybe `BlockResponse` should have a Header generic. What do you think?

2024-08-23 11:28 UTC, emhane commented
> @emhane, maybe `BlockResponse` should have a Header generic. What do you think?

block response does have generic header + transaction in form of associated types https://github.com/alloy-rs/alloy/blob/dbd9d7712da879ab1736a89caa37c2135fa9fafa/crates/network-primitives/src/traits.rs#L71-L74

2024-08-23 11:35 UTC, emhane approved these changes

2024-08-23 11:35 UTC, emhane commented on crates/rpc-types-eth/src/block.rs
> +impl Block<Header> {
```suggestion
impl Block<H> {
```
nitpick

2024-08-23 11:35 UTC, emhane commented on crates/rpc-types-eth/src/block.rs
> +impl<Header, T> BlockResponse for Block<Header, T> {
```suggestion
impl<H, T> BlockResponse for Block<H, T> {
```
nitpick

2024-08-23 16:50 UTC, merged

2024-08-23 22:05 UTC, klkvr commented
@emhane wdyt about switching generics order? it would turn this update into a non-breaking change and also seems more convenient as imo users are most likely to change the tx generic