Addition of engine rpc-types from reth
alloy-rs/alloy pull request #118
Opened 2024-01-16 22:01 UTC by 1010adigupta

## Motivation

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-01-16 22:10 UTC, 1010adigupta commented on crates/rpc-types/src/eth/transaction/request.rs
> +}
I have added BlobTransactionSidecar here which is the type for sidecar field for EIP-4844 transactions, in TransactionRequest, is this the correct approach or should I do this using other::OtherFields?

2024-01-16 23:02 UTC, mattsse requested changes
great draft!

I'd all of this in a new crate rpc-engine-types

2024-01-17 13:45 UTC, mattsse approved these changes
nice job!

now we can replace this in reth-rpc-types and simply reexport everything in the engine module there

2024-01-17 13:48 UTC, Evalir approved these changes
lgtm! thanks! just wanna make sure we're not copy extra unused deps

2024-01-17 13:48 UTC, Evalir commented on crates/rpc-engine-types/Cargo.toml
> +arbitrary = { version = "1.3", features = ["derive"], optional = true }
Do we need arbitrary?

2024-01-17 13:48 UTC, 1010adigupta commented
> nice job!
> 
> now we can replace this in reth-rpc-types and simply reexport everything in the engine module there

on it!
should I create a issue in reth for this, and attach a new pr there now?

2024-01-17 13:58 UTC, merged