refac: rm 2930 and 7702 - use alloy-rs/eips
alloy-rs/alloy pull request #1181
Opened 2024-08-23 06:56 UTC by yash-atreya

## Motivation

Ref #1174. 

## Solution

2930 and 7702 have been extracted to a new repo - https://github.com/alloy-rs/eips. Use that and re-export in alloy-eips.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-08-24 07:47 UTC, mattsse requested changes

2024-08-24 07:47 UTC, mattsse commented on crates/alloy/Cargo.toml
> -    "alloy-eips?/k256",
where did this go?

2024-08-24 07:47 UTC, mattsse commented on crates/eips/Cargo.toml
> +eip-7702 = { workspace = true }
.workspace

2024-08-24 07:47 UTC, mattsse commented on crates/eips/Cargo.toml
please avoid reformatting entries for these prs, makes it much harder to review

2024-08-26 06:38 UTC, yash-atreya commented on crates/alloy/Cargo.toml
> -    "alloy-eips?/k256",
Oversight, reintroduced

2024-08-26 09:37 UTC, onbjerg reviewed
let's update the alloy eips readme to point to the new repo so people know where to look for the code

2024-08-26 10:15 UTC, onbjerg approved these changes

2024-08-27 10:56 UTC, yash-atreya commented
Bumping `alloy-rs/eips` further requires #1167

2024-08-28 09:08 UTC, mattsse approved these changes

2024-08-28 09:08 UTC, merged