feat(rpc-types-engine): no-std support
alloy-rs/alloy pull request #1233
Opened 2024-09-04 11:23 UTC by refcell

### Description

Adds `no_std` for the `op-alloy-rpc-types-engine` crate.

2024-09-04 11:53 UTC, mattsse requested changes
let's also add this crate to

https://github.com/alloy-rs/op-alloy/blob/bd669da1ea0239411b317d81e30a0477aabb0808/scripts/check_no_std.sh#L4-L5

so we check in ci

2024-09-04 11:53 UTC, mattsse commented on crates/rpc-types-engine/src/lib.rs
> +#![cfg_attr(not(feature = "jwt"), no_std)]
this should use std feature to disable no_std

2024-09-04 11:53 UTC, mattsse commented on crates/rpc-types-engine/src/lib.rs
> +#[cfg(not(feature = "jwt"))]
same

2024-09-04 11:53 UTC, mattsse commented on crates/rpc-types-engine/Cargo.toml
>  default = ["jwt"]
this needs a std feature

2024-09-09 18:06 UTC, mattsse requested changes
nits

2024-09-09 18:06 UTC, mattsse commented on crates/rpc-types-engine/src/payload.rs
> +use alloc::{string::{ToString, String}, vec::Vec};
let's use extern crate alloc so we dont need to feature gate these

2024-09-09 18:06 UTC, mattsse commented on crates/rpc-types-engine/src/payload.rs
> +impl std::error::Error for PayloadError {}
this needs to impl fn source and return the rlp error

2024-09-09 18:06 UTC, mattsse commented on crates/rpc-types-engine/src/payload.rs
> +    Decode(alloy_rlp::Error),
this is now missing the from impl

2024-09-09 18:06 UTC, mattsse commented on crates/rpc-types-engine/src/forkchoice.rs
> +#[derive(Clone, Copy, Debug, PartialEq, Eq, derive_more::Display)]
once we bump msrv to 1.81 we can also use derive_more error and remove the feature entirely

https://docs.rs/derive_more/latest/derive_more/derive.Error.html

2024-09-10 15:45 UTC, refcell commented
Replaced with https://github.com/alloy-rs/alloy/pull/1268

2024-09-10 15:45 UTC, closed without merging