feat: Add iterator to BlobTransactionSidecar
alloy-rs/alloy pull request #1256
Opened 2024-09-07 14:48 UTC by DoTheBestToGetTheBest

closes

2024-09-09 12:52 UTC, mattsse requested changes

2024-09-09 12:52 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +pub struct BlobTransactionSidecarItem {
this should use the same serde attributes

2024-09-09 12:52 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +}
I don't think we need those, the existing error type should be sufficient

2024-09-09 12:52 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +}
this we don't need, there's a HashNum type already

2024-09-09 12:52 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +pub struct BlobTransactionSidecarItem {
this type should be moved below the existing sidecar impl

2024-09-11 17:43 UTC, DoTheBestToGetTheBest commented
hey matts thanks for the reivew, made all changes you requested!

2024-09-12 06:18 UTC, mattsse requested changes

2024-09-12 06:18 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +}
this is just alloy-serde::quantity

2024-09-12 06:18 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +
```suggestion
```

2024-09-12 06:18 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +}
this should be an IntoIter impl instead

2024-09-12 06:18 UTC, mattsse commented on crates/eips/src/eip4844/sidecar.rs
> +#[cfg(feature = "kzg")]
none of these should be necessary, this makes it very hard to read.

please use full paths instead, this way no import is required

2024-09-25 11:08 UTC, DaniPopes commented
Superseded by https://github.com/alloy-rs/alloy/pull/1334

2024-09-25 11:08 UTC, closed without merging