Replace assert_eq! with similar_asserts::assert_eq!
alloy-rs/alloy pull request #1429
Opened 2024-10-03 21:47 UTC by 0xriazaka

## Motivation
similar_asserts::assert_eq! highlights the exact differences between test subjects
Closes #1362 

## Solution
Replace assert_eq! with similar_asserts::assert_eq! on the "other" component

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-10-03 22:09 UTC, mattsse approved these changes

2024-10-03 22:16 UTC, mattsse requested changes

2024-10-03 22:16 UTC, mattsse commented on crates/serde/Cargo.toml
> +similar-asserts.workspace = true
this should actually be moved to dev-deps

2024-10-03 22:23 UTC, mattsse approved these changes

2024-10-03 22:25 UTC, mattsse commented
we def also want this in more tests in the rpc crates

2024-10-03 22:28 UTC, 0xriazaka commented
Sure will do that > we def also want this in more tests in the rpc crates

2024-10-04 07:17 UTC, mattsse requested changes

2024-10-04 07:17 UTC, mattsse commented on crates/rpc-client/src/builtin.rs
these don't make much sense, similar_asserts is mainly useful for checking serde json, so lets limit the scope of this pr to that

2024-10-04 22:13 UTC, 0xriazaka commented on crates/rpc-client/src/builtin.rs
check #1433

2024-10-07 03:49 UTC, 0xriazaka commented
resolved https://github.com/alloy-rs/alloy/pull/1433#discussion_r1788825627

2024-10-07 05:38 UTC, DaniPopes approved these changes
Thanks!

2024-10-07 13:00 UTC, merged