feat: serde helpers for hashmaps and btreemaps w/ quantity key types
alloy-rs/alloy pull request #1579
Opened 2024-10-29 04:56 UTC by stevencartavia

## Motivation

## Solution

## PR Checklist

- [ x] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-10-29 08:10 UTC, onbjerg requested changes
some comment nits,

this is also not quite right: we are only supposed to encode the keys as quantity, the value can be anything

2024-10-29 08:10 UTC, onbjerg commented on crates/serde/src/quantity.rs
> +/// Serde functions for encoding a hashmap of primitive numbers using the Ethereum "quantity"
```suggestion
/// Serde functions for encoding a `HashMap` of primitive numbers using the Ethereum "quantity"
```

2024-10-29 08:10 UTC, onbjerg commented on crates/serde/src/quantity.rs
> +    /// Serializes a hashmap of primitive numbers as a "quantity" hex string.
```suggestion
    /// Serializes a `HashMap` of primitive numbers as a "quantity" hex string.
```

2024-10-29 08:10 UTC, onbjerg commented on crates/serde/src/quantity.rs
> +    /// Deserializes a hashmap of primitive numbers from a "quantity" hex string.
```suggestion
    /// Deserializes a `HashMap` of primitive numbers from a "quantity" hex string.
```

2024-10-29 08:10 UTC, onbjerg commented on crates/serde/src/quantity.rs
> +/// Serde functions for encoding a BTreeMap of primitive numbers using the Ethereum "quantity"
```suggestion
/// Serde functions for encoding a `BTreeMap` of primitive numbers using the Ethereum "quantity"
```

2024-10-29 10:57 UTC, mattsse requested changes

2024-10-29 10:57 UTC, mattsse commented on crates/serde/src/quantity.rs
> +                let mut values = HashMap::new();
this can pre allocate with the map's size hint

2024-10-29 10:57 UTC, mattsse commented on crates/serde/src/quantity.rs
> +    pub fn serialize<K, V, S>(map: &HashMap<K, V>, serializer: S) -> Result<S::Ok, S::Error>
this should also relax the hasher generic, see for ref https://github.com/serde-rs/serde/blob/418062165f9fe395461db9f61569c3142c584854/serde/src/ser/impls.rs#L495-L506

2024-10-29 10:57 UTC, mattsse commented on crates/serde/src/quantity.rs
> +    pub fn deserialize<'de, K, V, D>(deserializer: D) -> Result<HashMap<K, V>, D::Error>
this should also relax the hasher

2024-10-30 04:15 UTC, stevencartavia commented
@onbjerg @mattsse, done with the requested changes! :)

2024-11-02 08:11 UTC, mattsse approved these changes

2024-11-02 08:24 UTC, merged