feat(consensus): public RlpEcdsaTx
alloy-rs/alloy pull request #1720
Opened 2024-11-30 21:04 UTC by htiennv

# Description

Public trait `RlpEcdsaTx` for implementation of `OpTypedTransaction`.

Ref: https://github.com/alloy-rs/op-alloy/issues/316

2024-12-02 09:45 UTC, mattsse requested changes
I think we can re-export but I'd like to use a separete `pub use` and mark this as `doc(hidden)` because this is considered private API and should only be used by other network impl like op-alloy, if we really need it

2024-12-12 06:04 UTC, htiennv commented
Hi @mattsse, i was updated. Can you check it? Thanks

2024-12-12 11:10 UTC, mattsse approved these changes

2024-12-12 11:17 UTC, mattsse reviewed
this is actually already exported

https://github.com/alloy-rs/alloy/blob/b0909d4650308918b2d552a641915ddb9c810f06/crates/consensus/src/transaction/mod.rs#L39-L40

transaction::RlpEcdsaTx

2024-12-12 11:17 UTC, closed without merging