feat: Migrate to `TrieAccount` from alloy-trie
alloy-rs/alloy pull request #1750
Opened 2024-12-04 16:13 UTC by moricho

## Motivation
`Account` has been migrated to `TrieAccount` of  alloy-trie in https://github.com/alloy-rs/trie/pull/65

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-12-04 17:57 UTC, mattsse requested changes
awesome, one nit

then we also want the conversion for genesis account seperately

2024-12-04 17:57 UTC, mattsse commented on crates/consensus/src/lib.rs
> +pub use alloy_trie::TrieAccount as Account;
can we also re-export TrieAccount and mark this rename as deprecated?

2024-12-04 20:36 UTC, mattsse approved these changes

2024-12-04 20:46 UTC, merged

2024-12-05 10:40 UTC, moricho commented
@mattsse I just saw your comment. Thank you for handling the genesis account conversion!

2024-12-05 10:42 UTC, mattsse commented
thank you!

I quickly pushed this over the line because we needed a new release on reth