feat: reth's block body fns
alloy-rs/alloy pull request #1775
Opened 2024-12-09 17:10 UTC by stevencartavia

## Motivation
https://github.com/paradigmxyz/reth/issues/12519

## Solution
Brought BlockBody fns from reth to replace reth's BlockBody type with alloy's

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-12-09 17:11 UTC, stevencartavia commented
I just brought these fns at the moment since the rest explicitly use `T: TransactionSigned`

2024-12-10 09:39 UTC, mattsse requested changes
cool, makes sense

one suggestion

2024-12-10 09:39 UTC, mattsse commented on crates/consensus/src/transaction/mod.rs
> +    }
these are no longer necessary with #1773

2024-12-11 10:54 UTC, mattsse requested changes
nits

2024-12-11 10:54 UTC, mattsse commented on crates/consensus/src/block/mod.rs
> +    }
this function is not needed and can be removed

2024-12-11 10:54 UTC, mattsse commented on crates/consensus/src/block/mod.rs
> +    }
this should be an impl Iterator instead because this is mostly useful when iterating over blob txs

2024-12-11 17:21 UTC, mattsse approved these changes

2024-12-11 17:31 UTC, merged