Add `try_spawn` function for Anvil and Geth bindings
alloy-rs/alloy pull request #226
Opened 2024-02-21 14:01 UTC by moricho

## Motivation
Closes: https://github.com/alloy-rs/alloy/issues/136

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-02-24 16:39 UTC, mattsse requested changes
this is a great start, we can now simplify the existing spawn functions by calling `try_spawn.expect`

2024-02-24 16:39 UTC, mattsse commented on crates/node-bindings/src/anvil.rs
> +    #[track_caller]
```suggestion
```

2024-02-25 15:23 UTC, moricho commented on crates/node-bindings/src/anvil.rs
> +    Spawn,
fixed at: https://github.com/alloy-rs/alloy/pull/226/commits/22168d69ae6f95cfb4402b3c2063e2b639cf99e2

2024-02-25 15:23 UTC, moricho commented on crates/node-bindings/src/anvil.rs
> +    #[track_caller]
fixed at: https://github.com/alloy-rs/alloy/pull/226/commits/263d850eef02d0fb92518324d8b20c9676caa939

2024-02-25 17:18 UTC, moricho commented
@mattsse 
Thanks for the review! 
I have tried to categorize some of the errors related to Geth. However, I am unsure if I have left anything out or if the categorization is accurate. If you have any suggestions or advice, I would appreciate your input.
https://github.com/alloy-rs/alloy/pull/226/files#diff-edd3384dd7db8fd08c3dfd953104f384359ab2f8211cdae1504eebd93ffbf38fR174-R210

2024-03-07 10:55 UTC, mattsse requested changes
sorry for the delay, 
error variants look fine,
last thing left to do is to change the `fn spawn` to 

```rust
fn spawn(&self) -> Instance {
   self.try_spawn().unwrap()
}
```

2024-03-07 12:24 UTC, moricho commented
Added the above change in https://github.com/alloy-rs/alloy/pull/226/commits/037a15f15cb9b350258869a6be263850721b6228

2024-03-07 12:53 UTC, mattsse approved these changes

2024-03-07 12:53 UTC, merged