feat: derive `Hash` for `TypedTransaction`
alloy-rs/alloy pull request #284
Opened 2024-03-12 15:30 UTC by onbjerg

## Motivation

This is needed for some caches in Foundry

## Solution

This was previously blocked by KZG types not being `Hash`

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-03-12 15:33 UTC, prestwich requested changes
For consistency, on `TxEnvelope` as well?

2024-03-12 15:33 UTC, DaniPopes approved these changes

2024-03-12 15:35 UTC, onbjerg commented
Blocked on c-kzg release on crates

2024-03-12 23:23 UTC, gakonst commented
https://github.com/ethereum/c-kzg-4844/releases/tag/v1.0.0 good to go!

2024-03-13 13:17 UTC, onbjerg commented
@gakonst we have not released c-kzg 1.0 on crates yet: https://crates.io/crates/c-kzg

2024-03-13 14:07 UTC, onbjerg commented
Published now

2024-03-13 14:14 UTC, DaniPopes approved these changes
l g m t

2024-03-13 14:14 UTC, merged