feat(examples): Port wallets examples from Ethers-rs
alloy-rs/alloy pull request #291
Opened 2024-03-13 09:03 UTC by zerosnacks

## Motivation

Adds first examples: `wallets`

## Solution

Ports the examples 

Includes setup of the initial example directory structure allowing you to run examples using the syntax: `cargo run --example mnemonic` where `mnemonic` is any example.

Makes two changes in `Alloy`:
- Enables default features for `coins-bip39`, exported from the `signer` crate so it includes wordlists.
- Clarifies comment of `eip712_signing_hash`.

Recommendations:
- Update name of `TrezorHDPath` to `HDPath` in line with Ledger's HDPath.

Suggestions for future examples:
- `AWS`
- `GCP`
- `Keystore`

Please consider I do not have access to all devices listed making it difficult to guarantee the correct functioning of the examples.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-03-13 14:01 UTC, DaniPopes commented on examples/wallets/Cargo.toml
> +alloy-transport-http = { workspace = true }
I think we should be using the `alloy` crates, wdyt @gakonst @mattsse ?

2024-03-13 14:11 UTC, DaniPopes commented on examples/wallets/Cargo.toml
> +alloy-transport-http = { workspace = true }
Also these should be inline syntax `.workspace = true` since we don't enable anything else

2024-03-13 17:18 UTC, onbjerg approved these changes

2024-03-13 17:27 UTC, prestwich requested changes
i am a strong NACK on examples crates in the workspace right now. These were a huge mess for ethers, and we haven't had a discussion on how to resolve that yet

2024-03-13 20:25 UTC, DaniPopes commented
@prestwich I don't see the concern with examples if we don't run them, only compile them. They're just like `no_run` doctests.

2024-03-13 21:26 UTC, prestwich commented
> @prestwich I don't see the concern with examples if we don't run them, only compile them. They're just like no_run doctests.
 
When making breaking changes, or updating recommended usage, an in-repo example depending on local packages needs to be updated on every PR, even ones that may never reach GA. Whereas homing examples in another repo and running a chron CI against both published and unpublished versions pushes all maintenance work out of the dev cycle and into the release cycle 

basically these likely belong in an `alloy-examples` and putting them here slows pace of development

2024-03-13 22:13 UTC, prestwich commented
Setting up a home for these
https://github.com/alloy-rs/examples

2024-03-14 15:53 UTC, zerosnacks commented on crates/signer/Cargo.toml
> +coins-bip39 = { version = "0.8.7", optional = true }
Note @zerosnacks 

Make sure to remove this after #309 is merged.

2024-03-14 16:54 UTC, zerosnacks commented
Closing in favor of https://github.com/alloy-rs/examples

2024-03-14 16:54 UTC, closed without merging