Porting transaction examples from ethers
alloy-rs/alloy pull request #302
Opened 2024-03-13 16:26 UTC by yash-atreya

## Motivation

Port transaction examples from `ethers` to `alloy`

## Solution

Added the following examples
- `decode_input`
- `transfer_eth`
- `transfer_erc20`
- `trace_transaction`
- `trace_call` - Uses trace_call as debug_traceCall is pending implementation
- `gas_price_usd`

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-03-13 16:27 UTC, yash-atreya commented
`ens` resolution can be implemented after extension crate for it has been completed.

2024-03-13 17:20 UTC, onbjerg requested changes

2024-03-13 17:20 UTC, onbjerg commented on examples/transactions/examples/transfer_erc20.rs
> +    let _tx = provider.get_transaction_by_hash(tx_hash).await?;
unused?

2024-03-13 17:20 UTC, onbjerg commented on examples/transactions/examples/transfer_erc20.rs
> +    let _tx = provider.get_transaction_by_hash(pending_tx.tx_hash().to_owned()).await?;
use pending tx to wait for the confirmation here

2024-03-13 17:20 UTC, onbjerg commented on examples/transactions/examples/transfer_eth.rs
> +    let bytes = hex::decode(input).unwrap();
formatting

2024-03-14 18:03 UTC, yash-atreya commented
Moved https://github.com/alloy-rs/examples/pull/4

2024-03-14 18:03 UTC, closed without merging