Feature duplicates
alloy-rs/alloy pull request #324
Opened 2024-03-15 17:00 UTC by JackG-eth

## Motivation

AccessList+Withdrawals should be moved to eips to prevent duplication

2024-03-16 13:07 UTC, mattsse requested changes
great start,

a few more todos!

2024-03-16 13:07 UTC, mattsse commented on crates/eips/src/withdrawal.rs
let's rename this eip4895.rs and documents, see also eip2930.rs

https://eips.ethereum.org/EIPS/eip-4895

this file also needs changes so serde is optional and we need ssz feature

2024-03-17 20:32 UTC, JackG-eth commented on crates/eips/Cargo.toml
> +serde_json.workspace = true
moved

2024-03-17 20:36 UTC, JackG-eth commented on crates/eips/src/withdrawal.rs
Added optionality of serde, is this as some packages need it and others don't pushing more performance?

2024-03-17 20:37 UTC, JackG-eth commented on crates/eips/src/withdrawal.rs
Do you mean szz feature for eip2930? as it already exists for withdrawals.

2024-03-18 10:58 UTC, mattsse requested changes

2024-03-18 10:58 UTC, mattsse commented on crates/eips/src/eip4895.rs
>  #[cfg_attr(feature = "ssz", derive(ssz_derive::Encode, ssz_derive::Decode))]
this feature currently does not exist in this crate, so we need to add this and the required deps, see rpc-types for reference
then we have to enable this in rpc-types if the ssz feature is enabled there

2024-03-21 11:34 UTC, mattsse approved these changes

2024-03-21 11:37 UTC, mattsse commented
fyi @klkvr with this AccessList types are deduplicated

2024-03-22 13:01 UTC, onbjerg commented
can you also remove https://github.com/alloy-rs/alloy/blob/e8c622c713938cd2ede29d6b38d2aaa009dd3ad5/crates/network/src/ethereum/builder.rs#L229 which was part of the motivation for this PR?

2024-03-22 13:01 UTC, onbjerg requested changes
(see above)

2024-03-22 13:02 UTC, mattsse commented
done

2024-03-22 13:04 UTC, onbjerg approved these changes
lgtm

2024-03-22 13:20 UTC, merged