feat: helpers for AnyNetwork
alloy-rs/alloy pull request #476
Opened 2024-04-06 11:05 UTC by klkvr

## Motivation

Small changes for https://github.com/foundry-rs/foundry/pull/7106

Adds `AnyNetworkSigner` and alias for `AnyNetwork::ReceiptResponse` as it's pretty long

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-04-06 12:08 UTC, Evalir approved these changes

2024-04-06 12:08 UTC, Evalir commented on crates/network/src/any/signer.rs
> +pub struct AnyNetworkSigner(Arc<dyn TxSigner<Signature> + Send + Sync>);
makes sense to make this `Arc` so we can share the same signer

2024-04-06 12:16 UTC, DaniPopes approved these changes

2024-04-06 12:28 UTC, mattsse requested changes
not sure if it makes sense to duplicate the signer type,

Perhaps for forward compatibility we can do that, in case we want to support more tx types that are don't exist on ehtereum (currently there aren't any)

so I think for now we can simply use the ethereumsigner for AnyNetwork as well but add `impl NetworkSigner<AnyNetwork> for EthereumSigner {` because both networks have the same `UnsignedTx`

I believe we could even do

```rust
impl<N> NetworkSigner<N> for EthereumSigner
    where N: Network<UnsignedTx= TypedTransaction, TxEnvelope = TxEnvelope >
        {
```

wdyt @prestwich

2024-04-06 12:28 UTC, mattsse commented on crates/network/src/any/mod.rs
> +pub type AnyReceipt = WithOtherFields<TransactionReceipt<AnyReceiptEnvelope<Log>>>;
could move this to rpc types and rename `AnyTransactionReceipt`?

2024-04-06 15:37 UTC, prestwich commented
supportive of type-reuse and the blanket impl

The reason that `NetworkSigner<N>` is a trait and not an assoc type is to allow many different objects to be network signers. We could even do a blanket like `impl<T, Sig> NetworkSigner<Ethereum> for T where T: Signer<Sig>` if it doesn't cause unconstrained type param issues`

2024-04-06 15:39 UTC, prestwich commented
basically the idea of `NetworkSigner<N>` is "any object that can sign any subset of transactions allowed by the network"

2024-04-07 11:30 UTC, mattsse approved these changes

2024-04-07 11:35 UTC, merged