[Feature] Receipt trait in alloy-consensus
alloy-rs/alloy pull request #477
Opened 2024-04-06 16:54 UTC by developeruche

## Motivation
 Closes #466

## Solution

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-04-06 21:15 UTC, developeruche commented
@prestwich *change status function on rpc receipt type to delegate to Receipt implementation of inner* 

This is not quite possible at the moment;

pub enum ReceiptEnvelope<T = Log>  ----> This uses Log from `use alloy_primitives::{Bloom, Log};`

and 

pub struct TransactionReceipt<T = ReceiptEnvelope<Log>> ----> This uses Log from `rpc-type` making the trait bound not satified... that's is `Receipt implementation of inner` is not accessiable

2024-04-22 14:31 UTC, prestwich requested changes

2024-04-22 14:31 UTC, prestwich commented on crates/consensus/src/receipt/any.rs
> +impl TxReceipt for AnyReceiptEnvelope {
this should now be generic over `T` 

`impl<T> TxReceipt for AnyReceiptEnvelope<T>`

2024-04-22 14:31 UTC, prestwich commented on crates/consensus/src/receipt/any.rs
> +    fn logs(&self) -> &[Log] {
this will probably need to be `-> &[T]`

2024-04-22 14:31 UTC, prestwich commented on crates/consensus/src/receipt/envelope.rs
> +impl TxReceipt for ReceiptEnvelope {
same, this should be generic over `T`

2024-04-22 14:31 UTC, prestwich commented on crates/network/src/lib.rs
> +    type ReceiptEnvelope: Eip2718Envelope + TxReceipt;
the `type ReceiptResponse` below should also have a `+ TxReceipt` bound

2024-04-23 13:22 UTC, prestwich approved these changes

2024-04-23 13:27 UTC, merged

2024-04-23 13:28 UTC, prestwich commented on crates/consensus/src/receipt/receipts.rs
> -    fn success(&self) -> bool {
followup work:
- Make this impl generic over <T>