Imp From rpc-types to primitives Log
alloy-rs/alloy pull request #50
Opened 2023-11-29 21:44 UTC by leruaa

Came across the following use case:

- Retrieve logs with `Provider::get_logs()` that returns a `Vec` of `alloy_rpc_types::Log`
- Then decode logs using `SolEvent::decode_log_object()` that accept a `alloy_primitives::Log`

So I needed to convert `alloy_rpc_types::Log` to `alloy_primitives::Log`, hence this PR.

2023-11-29 21:53 UTC, Evalir requested changes
looks good! i have a nit:

2023-11-29 21:53 UTC, Evalir commented on crates/rpc-types/src/eth/log.rs
> +    /// The topics are invalid
I would prefer something a bit more specific, as the invalid case here is having _too many_ topics. Maybe `LogError::TooManyTopics`?

2023-11-29 22:02 UTC, prestwich commented
@Evalir this ties back to the conversation we were having in telegram the other day. Should RPC types instead embed a primitive Log?

2023-11-29 22:08 UTC, Evalir commented
@prestwich I think it should—this rpc type is a fuller version of the log object, and the additional APIs from the primitive log add additional safety. However, there's some work to do if we want to embed it here:
- `alloy_primitives::Log` should be `LogData`, as `Log` omits the emitter (as you said on tg)
- We then need to add a `Log` type with the emitter. This can then also remove the `raw_log.rs` type which is essentially the primitive log with the emitter.
- Finally, we can embed `Log` into this rpc type.

2023-11-29 22:27 UTC, leruaa commented
@Evalir Updated following your comment.

 Would you like I create an issue for the bigger refactoring you mentioned? I would be happy to work on this.

2023-11-30 03:39 UTC, prestwich commented
> * `alloy_primitives::Log` should be `LogData`, as `Log` omits the emitter (as you said on tg)
> * We then need to add a `Log` type with the emitter. This can then also remove the `raw_log.rs` type which is essentially the primitive log with the emitter.
> * Finally, we can embed `Log` into this rpc type.

Is there a good way to make it generic over encoded and decoded logs? E.g. can we achieve something like this

```
struct Log<T = LogData> {
    emitter: Address,
    inner: T,
}

impl Log<LogData> { 
    fn try_decode<T: SolEvent>(self) -> Result<Log<T>, Self>;
} 
impl Log<T> where T: sol_types::SolEvent { 
    fn encode(self) -> Log<LogData>;
}

impl RlpEncodable for Log<LogData> { ... }
impl RlpEncodable for Log<T> where T: sol_types::SolEvent { ... }
```

2023-12-18 16:09 UTC, gakonst approved these changes

2023-12-18 16:09 UTC, merged