feat: Export inner encoding / decoding functions from `Tx*` types
alloy-rs/alloy pull request #529
Opened 2024-04-13 20:15 UTC by clabby

## Overview

Exports a few of the `Tx*` types' inner encoding & decoding functions for use in the `op-alloy-consensus` wrapper. Doing so allows us to re-use all of these types in the expanded transaction envelope enum.

2024-04-14 13:17 UTC, mattsse requested changes
doc nit

I think we need to make them pub so that the tx types can be reused externally, for example in a network specific enum that needs to implement rlp

2024-04-14 13:17 UTC, mattsse commented on crates/consensus/src/transaction/eip1559.rs
> +    pub fn fields_len(&self) -> usize {
can we also update the docs here, because they are incorrect

2024-04-14 22:13 UTC, prestwich commented
i agree that we need to do this. i would like to open a follow up issue for improving naming

2024-04-15 11:35 UTC, mattsse requested changes
can we mark these as `#[doc(hidden)]`? so that they don't show up in autosuggestions

2024-04-16 09:57 UTC, prestwich approved these changes

2024-04-16 09:57 UTC, merged