feat: add generics to filter, block, transaction, and pub_sub.
alloy-rs/alloy pull request #573
Opened 2024-04-18 19:54 UTC by EmperorOrokuSaki

## Motivation

In order to be able to use several structs and types from this repository for the Optimism port, they should take generics that can be replaced/used with the optimism types. This is not ready for review, yet. It's a draft.

## Solution

Add generics to the necessary structs and types.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-04-19 00:29 UTC, prestwich commented on crates/rpc-types/src/eth/block.rs
> +pub enum BlockTransactions {
why is this getting less generic?

2024-04-19 06:51 UTC, EmperorOrokuSaki commented on crates/rpc-types/src/eth/block.rs
> +pub enum BlockTransactions {
Ah that was a mistake. Good catch

2024-04-19 08:27 UTC, prestwich commented
In favor of making the code reusable by other networks. At what point is this PR done? do we have a list of types we need to update?

2024-04-19 09:32 UTC, mattsse commented
> At what point is this PR done?

this process will take a few iterations because when adding new network specific types we'll discover more things that could be reused.

I think we will run into a few issues with types that have multiple network specific fields, like Transactions,Logs,Block,Header, for which we either need to add a bunch of generics or also do some kind of network trait with associated types...

perhaps, at some point it's just easier to simply duplicate the types but not sure if we want to

2024-04-19 09:34 UTC, EmperorOrokuSaki commented
The block struct also needs to take a generic for example but that means many other dependent structs will need the same thing later. Making Transaction a trait here would solve such issue for example.
So far for optimism rpc types everything needed to take a generic, takes it with this pr (except block as that depends on the trait discussion)

2024-04-19 09:34 UTC, mattsse requested changes
these are reasonable,

I think we could also restrict this to `: Transaction`

2024-04-19 09:35 UTC, mattsse approved these changes

2024-04-19 09:51 UTC, EmperorOrokuSaki commented
> these are reasonable,
> 
> I think we could also restrict this to `: Transaction`

Just updated that. We can add the log generic later when needed probably

2024-04-20 08:59 UTC, EmperorOrokuSaki commented
Can we merge this? @mattsse @prestwich

2024-04-20 09:16 UTC, merged