feat: add builder methods
alloy-rs/alloy pull request #591
Opened 2024-04-20 20:07 UTC by EmperorOrokuSaki

## Motivation
Issue #583 

## Solution
Implement builder methods for all fields

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-04-21 09:14 UTC, mattsse requested changes
ty,
some nits

2024-04-21 09:14 UTC, mattsse commented on crates/rpc-types-trace/src/filter.rs
> +    pub fn with_from_block(&mut self, block: u64) -> &mut Self {
these should all consume `self` and return `Self`

2024-04-21 09:14 UTC, mattsse commented on crates/rpc-types-trace/src/filter.rs
can drop the `with_` prefix, is cleaner imo

2024-04-21 09:14 UTC, mattsse commented on crates/rpc-types-trace/src/geth/mod.rs
> +    pub fn with_tracing_options(&mut self, options: GethDebugTracingOptions) -> &mut Self {
here we can keep the with_ but also change fro &mut self to self

2024-04-22 10:37 UTC, prestwich approved these changes

2024-04-22 10:37 UTC, merged