`alloy_rpc_types_engine`: expose inner `B64` from `PayloadId`
alloy-rs/alloy pull request #646
Opened 2024-04-28 14:48 UTC by ralexstokes

There is currently no way to access the inner `B64` of the `PayloadId` type.

This means you cannot reuse the computation that derives the payload bytes.

My use case is a custom payload builder on top of `reth` that attaches additional payload builder attributes beyond what the Engine API provides: https://github.com/ralexstokes/mev-rs/blob/main/mev-build-rs/src/payload/builder_attributes.rs#L71-L77

I would like to use the same `PayloadId` that `reth` natively provides and simply mix in new data into the payload id by mixing in new data, e.g. https://github.com/ralexstokes/mev-rs/blob/0d283373445c36a6287f1c51599ddd662fbe7c2a/mev-build-rs/src/payload/builder_attributes.rs#L47

Without this, I have to locally vendor the same computation as `reth` and also pass around the bytes along with the `PayloadId` type (see return signature here: https://github.com/ralexstokes/mev-rs/blob/0d283373445c36a6287f1c51599ddd662fbe7c2a/mev-build-rs/src/payload/builder_attributes.rs#L17)

2024-04-28 14:52 UTC, prestwich approved these changes

2024-04-28 14:58 UTC, mattsse requested changes
I think this should be a getter instead to prevent &mut access

2024-04-28 15:02 UTC, prestwich commented
@mattsse should be `as_ref()` then? although it sounds like @ralexstokes wants mutable access?

2024-04-28 15:07 UTC, mattsse approved these changes
I see,
should be fine

2024-04-28 15:07 UTC, merged

2024-04-29 14:29 UTC, ralexstokes commented
im fine to just copy the bytes out and construct a new `PayloadId` instance

before this PR, there was just no way to do so