feat: simple `IPC` test
alloy-rs/alloy pull request #65
Opened 2023-12-06 19:10 UTC by Evalir

## Motivation

IPC had not test for making a request

## Solution

Adds a simple sanity test using the geth binary (we can switch it out for a mock later)

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2023-12-06 19:12 UTC, DaniPopes requested changes

2023-12-06 19:12 UTC, DaniPopes commented on .github/scripts/install_test_binaries.sh
> +main
```suggestion
main

```

2023-12-06 19:16 UTC, prestwich commented on .github/scripts/install_test_binaries.sh
> +    wait $g $!
i would really love not to install geth in our tests, is there an expedient way we can do this with a mock? 😮‍💨

2023-12-06 19:21 UTC, Evalir reviewed
@prestwich seems like the ipc client doesn't read the stream at all and it times out? https://github.com/alloy-rs/alloy/actions/runs/7119215013/job/19383813553

2023-12-08 17:47 UTC, Evalir reviewed
test passes now @prestwich — any chance we can merge like this and clean up geth later?

2023-12-08 20:14 UTC, merged