feat: add `EngineApi` extension trait
alloy-rs/alloy pull request #676
Opened 2024-05-03 19:35 UTC by leruaa

Closes  #658

2024-05-03 22:47 UTC, onbjerg requested changes
this is missing https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md

2024-05-04 05:23 UTC, mattsse requested changes
nice, smol nit

2024-05-04 05:23 UTC, mattsse commented on crates/provider/Cargo.toml
> +engine = ["dep:alloy-rpc-types-engine"]
```suggestion
engine-api = ["dep:alloy-rpc-types-engine"]
```

2024-05-04 05:23 UTC, mattsse commented on crates/provider/src/ext/engine.rs
> +pub trait EngineApi<N, T>: Send + Sync {
this should make a note that the provider should use  JWT authentication layer

2024-05-05 20:24 UTC, onbjerg requested changes
otherwise lgtm

2024-05-05 20:24 UTC, onbjerg commented on crates/provider/src/ext/engine.rs
> +    /// See also <https://github.com/ethereum/execution-apis/blob/main/src/engine/identification.md#engine_getclientversionv1>
let's add a small doc explaining that the param is the CL client version

2024-05-06 21:07 UTC, mattsse approved these changes

2024-05-06 21:07 UTC, merged