Specific Configs to GethDebugTracerConfig + generic config build method for GethDebugTracingOptions
alloy-rs/alloy pull request #686
Opened 2024-05-05 13:39 UTC by halo3mic

## Motivation

1. Simpler conversion from specific tracer config to GethDebugTracerConfig
2. Single config build method on GethDebugTracingOptions that covers all configs 

## Solution

1. Impl From for CallConfig, PreStateConfig, MuxConfig
2. Introduce generic build method for trace configs on GethDebugTracingOptions

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-05-05 19:14 UTC, DaniPopes approved these changes

2024-05-05 19:14 UTC, DaniPopes commented
cc @mattsse

2024-05-13 15:32 UTC, mattsse requested changes

2024-05-13 15:32 UTC, mattsse commented on crates/rpc-types-trace/src/geth/mod.rs
>          self
can we keep this functions?

2024-05-15 13:20 UTC, mattsse commented on crates/rpc-types-trace/src/geth/mod.rs
>          self
yeah, and having them doesn't hurt

2024-05-21 21:15 UTC, yash-atreya commented
@halo3mic are you still on this? Else I can take this over, we'd like to wrap it up

2024-05-22 08:53 UTC, mattsse approved these changes

2024-05-22 08:53 UTC, merged