chore(other): use type aliases where possible to improve clarity
alloy-rs/alloy pull request #859
Opened 2024-06-10 11:23 UTC by zerosnacks

## Motivation

Reduces magic values and makes it easier for end-users to see what value they are getting e.g. `TxHash` instead of `FixedBytes<32>` when `watch()`-ing a transaction.

## Solution

Should have no impact and no logic changes should be present.

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-06-10 11:39 UTC, zerosnacks commented on crates/eips/src/eip1898.rs
>      }
Note, left this as changed to open discussion - I've generally opted for not using the alias for `From` impl's, curious what is preferred in this case:

- Change all where useful
- Do not change any

2024-06-11 11:57 UTC, zerosnacks commented on crates/genesis/src/lib.rs
> +    pub timestamp: BlockTimestamp,
Reverted this for `genesis`, considering it is almost always just read from a JSON config, rarely dynamically.

2024-06-11 13:51 UTC, zerosnacks commented on crates/consensus/src/transaction/eip1559.rs
> +use alloy_primitives::{aliases::TxNonce, keccak256, Bytes, ChainId, Signature, TxKind, U256};
`TxNonce` is now exported correctly see but unfortunately not part of the `0.7.6` release: https://github.com/alloy-rs/core/pull/655

2024-06-11 13:52 UTC, zerosnacks commented on crates/consensus/src/transaction/eip1559.rs
> +    }
Goal of these changes is cosmetic, simply enforcing consistent ordering for clarity

2024-06-11 13:59 UTC, zerosnacks commented on crates/provider/src/ext/anvil.rs
> +        timestamp: BlockTimestamp,
Fixes incorrect parameter name

2024-06-11 15:30 UTC, mattsse requested changes
I'm very much against using aliases for nonce and timestamp, this is just confusing.

2024-06-11 17:51 UTC, zerosnacks commented
@mattsse 

> I'm very much against using aliases for nonce and timestamp, this is just confusing.

I've removed the number aliases, kept the hash aliases as discussed

Any existing references using the number-type aliases I've kept around, just avoided introducing any new ones.

2024-06-11 17:51 UTC, zerosnacks commented on crates/consensus/src/transaction/eip1559.rs
> +use alloy_primitives::{aliases::TxNonce, keccak256, Bytes, ChainId, Signature, TxKind, U256};
Not relevant anymore

2024-06-12 10:59 UTC, mattsse approved these changes

2024-06-12 10:59 UTC, merged