feat: use reth-rpc-types
alloy-rs/alloy pull request #89
Opened 2023-12-18 17:23 UTC by mattsse

move all of reth-rpc-types to alloy-rpc-types.

2023-12-24 18:10 UTC, DaniPopes requested changes

2023-12-24 18:10 UTC, DaniPopes commented on crates/rpc-types/Cargo.toml
> +ssz = ["dep:ethereum_ssz" ,"dep:ethereum_ssz_derive", "alloy-primitives/ssz"]
We should keep the `jsonrpsee` feature instead of using implicit features.

2023-12-24 18:10 UTC, DaniPopes commented on crates/rpc-types/src/eth/fee.rs
> +    #[serde(skip_serializing_if = "Option::is_none")]
Is this intentional?

2024-01-04 14:10 UTC, Evalir approved these changes

2024-01-04 14:22 UTC, merged