feat(provider): support ethCall optional blockId serialization
alloy-rs/alloy pull request #900
Opened 2024-06-14 14:04 UTC by zerosnacks

## Motivation

Closes #896 

## Solution

- Implements optional serialization of block, correctly handling the `len`

## PR Checklist

- [ ] Added Tests
- [ ] Added Documentation
- [ ] Breaking changes

2024-06-14 14:52 UTC, mattsse requested changes
could we also add a simple serde test ethcallparams?

2024-06-14 14:52 UTC, mattsse commented on crates/provider/src/provider/call.rs
> +        }
here we need to always serialize if overrides are set because overrides must be third argument

2024-06-17 12:34 UTC, DaniPopes commented on crates/provider/src/provider/call.rs
> +
```suggestion
```

2024-06-17 12:37 UTC, mattsse requested changes

2024-06-17 12:37 UTC, mattsse commented on crates/provider/Cargo.toml
> +serde_json = { workspace = true, features = ["preserve_order"] }
please undo, we dont want to enable this because this can cause a ton of side-effects

2024-06-17 12:48 UTC, merged