feat: add missing admin_* methods
alloy-rs/alloy pull request #991
Opened 2024-06-29 09:06 UTC by alexfertel

## Motivation

Adds missing `admin_*` RPC methods. Work towards completing #926. 

## Solution

I may need some help with this, because I don't have an easy way to test this, since they are admin methods.

- Decided on a return type of `Option<u16>` because even though the docs say that a subscription id is returned, I see that `reth` returns a [`jsonrpsee::core::SubscriptionResult`](https://github.com/paradigmxyz/reth/blob/57c4f7e570c7fac06929c7bc035ae3e3df87ea81/crates/rpc/rpc/src/admin.rs#L135), which is a `Result<(), StringError>` and not an id. Lmk if this is not correct.
- The docs say `admin_peerEvents`, however, Geth errors with `the method admin_peerEvents does not exist/is not available`. `admin_peerEvents_subscribe` works fine.
- Decided on using `u16` for subscription ids because of [Geth's implementation](https://github.com/ethereum/go-ethereum/blob/7cfff30ba3a67de767a9b2a7405b91f120873d10/rpc/subscription.go).

## PR Checklist

- [ ] Added Tests
- [x] Added Documentation
- [ ] Breaking changes

2024-06-29 09:14 UTC, alexfertel commented
Interestingly, the `wasm-wasi` check also fails on `main`.

2024-06-29 12:31 UTC, mattsse requested changes
ty, this is a subscription for

https://github.com/ethereum/go-ethereum/blob/473ee8fc07a3f89cf3978e164a6fad218de9a6b5/p2p/peer.go#L92-L103

and it looks like we're missing this type in the admin crate

2024-06-29 12:34 UTC, DaniPopes commented
> 
Interestingly, the wasm-wasi check also fails on main. Unsure why ext::anvil::tests::test_anvil_set_interval_mining fails on windows. Damn, why is this PR breaking this stuff...

Not your fault, fixed on main

2024-06-29 12:39 UTC, mattsse commented
@alexfertel 

see also 

https://github.com/alloy-rs/alloy/blob/1807965627d29a3e6d9cab7774da1d92be971df5/crates/rpc-client/src/call.rs#L202-L208

"eth_subscribe" is detected as subscription by default, for others we'd need to set it after calling ".request("admin_peeEvents").set_is_subscription"

2024-06-29 14:03 UTC, alexfertel commented
@mattsse Does this make more sense?

I'm worried that `PeerEvent` may not serialize/deserialize correctly, is there a place where I can find a few json examples of the responses so that I can test this?

2024-06-29 16:01 UTC, DaniPopes commented on crates/provider/src/ext/admin.rs
> +    /// To unsubscribe from peer events, call `unsubscribe_peer_events`.
doc is outdated

2024-07-03 17:41 UTC, DaniPopes approved these changes
Thanks!

2024-07-03 17:51 UTC, merged